---

- name: Remove SWAP file
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable SWAP
  shell: swapoff -a

- name: Disable SELINUX
  shell: setenforce 0

- replace:
  path: /etc/selinux/config
  regexp: 'SELINUX=enforcing'
  replace: 'SELINUX=permissive'
  backup: no

- name: Install kubeadm packages
  yum:
    name: "{{ item }}"
    allow_downgrade: yes
  with_items:
    - kubelet-{{ kubelet_version }}
    - kubeadm
    - kubectl

- name: set docker cgroup-driver
  shell: docker info 2>/dev/null |grep -i cgroup | cut -d":" -f2 | tr -d " "
  register: docker_cgroup_driver

- replace:
  path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  regexp: '--cgroup-driver=(systemd|cgroupfs)'
  replace: '--cgroup-driver={{docker_cgroup_driver.stdout}}'
  backup: no

- replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: 'cadvisor-port=0'
    replace: 'cadvisor-port=4194'
    backup: no

- name: modprobe
  command: modprobe br_netfilter

- name: Add netbridge ipv4
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    state: present
    create: yes

- name: Add netbridge ipv6
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.bridge.bridge-nf-call-ip6tables = 1'
    state: present
    create: yes

- name: update sysctl
  command: sysctl --system

