---

- name: install ntpd
  yum:
    name: ntp
    state: present

- name: stop ntpd service
  service:
    name: ntpd
    state: stopped

- name: sync time
  command: ntpd -gq

- name: start ntpd service
  service:
    name: ntpd
    state: restarted
    enabled: yes
