---

- name: Install docker dependencies
  yum:
    name: "{{item}}"
  with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - policycoreutils-python

- name: Installs docker
  yum: 
    name: docker-ce-{{docker_version}} # docker in some distros
    state: installed
  
- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes

